#!/usr/bin/env python3
import random
import requests
from bs4 import BeautifulSoup
import webbrowser
import subprocess


def get_builtin_url():
    url = 'https://builtin.com/jobs/remote/mid-level'
    html = requests.get(url).text
    soup = BeautifulSoup(html, 'html.parser')
    last_page = int(soup.select("li[class='mx-xs page-item'] a")[-1].text)
    rand_page = random.randint(1, last_page)
    rand_url = f"{url}?page={rand_page}"
    return rand_url


def get_linkedin_url():
    url = 'https://www.linkedin.com/jobs/search/?keywords=&location=United%20States&f_TPR=&f_WT'
    rand_page = random.randint(1, 5000)
    rand_url = f"{url}&start={rand_page}"
    return rand_url


if __name__ == "__main__":
    # webbrowser.open_new_tab(rand_url)

    builtin_url = get_builtin_url()
    print(builtin_url)
    webbrowser.open_new_tab(builtin_url)

    linkedin_url = get_linkedin_url()
    print(linkedin_url)
    webbrowser.open_new_tab(linkedin_url)

