call plug#begin('~/.vim/plugged')
Plug 'patstockwell/vim-monokai-tasty'
" Plug 'morhetz/gruvbox'
Plug 'vim-python/python-syntax'
call plug#end()
let g:python_highlight_all = 1
" colorscheme gruvbox
" let g:gruvbox_contrast_dark='hard'
let g:vim_monokai_tasty_italic=1
colorscheme vim-monokai-tasty
" highlight Normal ctermbg=black

" When started as "evim", evim.vim will already have done these settings, bail
" out.
if v:progname =~? "evim"
  finish
endif

" Get the defaults that most users want.
source $VIMRUNTIME/defaults.vim

if &t_Co > 2 || has("gui_running")
  " Switch on highlighting the last used search pattern.
  set hlsearch
endif

" Put these in an autocmd group, so that we can delete them easily.
augroup vimrcEx
  au!

  " For all text files set 'textwidth' to 78 characters.
  autocmd FileType text setlocal textwidth=78
augroup END

" Add optional packages.
"
" The matchit plugin makes the % command work better, but it is not backwards
" compatible.
" The ! means the package won't be loaded right away but when plugins are
" loaded during initialization.
if has('syntax') && has('eval')
  packadd! matchit
endif

set ic  "ignore-case
set is  "partial-search-match
set number  "line-numbers
set mouse=  "no-mouse
set ttymouse=  "no-mouse
set directory=/tmp
set backupdir=/tmp
set undofile  " keep an undo file (undo changes after closing)
set undodir=~/.vim/undodir  "put all undo files in a tidy dir
set background=dark
set tabstop=4 shiftwidth=4 expandtab  " :retab to convert tabs to spaces
