# ~/.bashrc ~/.bash_profile  ~/.bash_login
PS1="\e[1;31m\u\e[m@\e[1;33m\h\e[m:\e[1;34m\w\e[m\n\e[1;32m\$\e[m \[$(tput sgr0)\]"
export TERM="xterm-256color"
alias ls='ls -1 --color'
# alias thesr='/usr/bin/python3 /home/john/Documents/Thesaurus_Rex/thesr.py'

