# ~/.bashrc ~/.bash_profile  ~/.bash_login
export PS1="\[\e[1;31m\]\u\[\e[m\]@\[\e[1;33m\]\h\[\e[m\]:\[\e[1;34m\]\w\[\e[m\]\r\n\[\e[1;32m\]\$\[\e[m\] \[$(tput sgr0)\]"
export TERM="xterm-256color"
source ~/.venv/bin/activate
