SELECT DISTINCT GRANTEE, TCREATOR, TTNAME
FROM SYSIBM.SYSTABAUTH
WHERE TCREATOR LIKE '%REAL_ESTATE%';

SELECT DISTINCT AUTHID
FROM SYSIBMADM.PRIVILEGES
WHERE AUTHID = SESSION_USER AND AUTHIDTYPE = 'U'
  AND (
    OBJECTSCHEMA LIKE '%REAL_ESTATE%'
    OR OBJECTNAME LIKE '%CSIM%'
  )
WITH UR;

SELECT DISTINCT GRANTEE
FROM SYSCAT.TABAUTH
WHERE (
  TABSCHEMA LIKE '%REAL_ESTATE%'
  OR TABNAME LIKE '%CSIM%'
)
WITH UR;
