WITH UNIQUES AS (
    SELECT
    DISTINCT WEIRD_COL
    FROM SCHEMA.TABLE
)
SELECT
    WEIRD_COL, LENGTH(WEIRD_COL) LEN
FROM UNIQUES
ORDER BY LEN DESC
WITH UR;


-- DB2 SQL Error: SQLCODE=-803, SQLSTATE=23505, SQLERRMC=2;EPM_FINANCE.DIM_DEVELOPMENT_PROJECT_FLAT_BLUE, DRIVER=4.32.28
SELECT INDNAME, INDSCHEMA, COLNAMES, *
FROM SYSCAT.INDEXES
WHERE IID = 2  -- SQLERRMC
  AND TABSCHEMA = 'EPM_FINANCE'
  AND TABNAME = 'DIM_DEVELOPMENT_PROJECT_FLAT_BLUE'
