-- period mnemonics, underflow
SELECT *
  CASE
    WHEN YEAR_NUM = REF_YEAR
      THEN 'CY'
    WHEN YEAR_NUM = (REF_YEAR - 1)
      THEN 'PY'
    WHEN YEAR_NUM = (REF_YEAR - 2)
      THEN 'PPY'
  END MNEMONIC_YEAR,
  CASE
    WHEN QUARTER_NUM = REF_QUARTER
      THEN 'CM'
    WHEN QUARTER_NUM = (CASE WHEN (((REF_QUARTER - 1) < 1) AND MNEMONIC_YEAR <> 'CY') THEN (REF_QUARTER - 1 + 4) ELSE (REF_QUARTER - 1) END)
      THEN 'PQ'
    WHEN QUARTER_NUM = (CASE WHEN (((REF_QUARTER - 2) < 1) AND MNEMONIC_YEAR <> 'CY') THEN (REF_QUARTER - 2 + 4) ELSE (REF_QUARTER - 2) END)
      THEN 'PPQ'
  END MNEMONIC_QUARTER,
  CASE
    WHEN MONTH_NUM = REF_MONTH
      THEN 'CM'
  WHEN MONTH_NUM = (CASE WHEN (((REF_MONTH - 1) < 1) AND MNEMONIC_YEAR <> 'CY') THEN (REF_MONTH - 1 + 12) ELSE (REF_MONTH - 1) END)
    THEN 'PM'
  WHEN MONTH_NUM = (CASE WHEN (((REF_MONTH - 2) < 1) AND MNEMONIC_YEAR <> 'CY') THEN (REF_MONTH - 2 + 12) ELSE (REF_MONTH - 2) END)
    THEN 'PPM'
  END MNEMONIC_MONTH
FROM SCHEMA.TABLE;
