SELECT DISTINCT GRANTEE, TCREATOR, TTNAME
FROM SYSIBM.SYSTABAUTH
WHERE TCREATOR LIKE '%REAL_ESTATE%';

SELECT DISTINCT AUTHID
FROM SYSIBMADM.PRIVILEGES
WHERE AUTHID = SESSION_USER AND AUTHIDTYPE = 'U'
  AND (
    OBJECTSCHEMA LIKE '%REAL_ESTATE%'
    OR OBJECTNAME LIKE '%CSIM%'
  )
WITH UR;

SELECT DISTINCT GRANTEE
FROM SYSCAT.TABAUTH
WHERE (
  TABSCHEMA LIKE '%REAL_ESTATE%'
  OR TABNAME LIKE '%CSIM%'
)
WITH UR;

-- User's roles (replace SESSION_USER with '<user>')
SELECT myauth.GRANTEE, myauth.ROLENAME
FROM TABLE (SYSPROC.AUTH_LIST_ROLES_FOR_AUTHID (SESSION_USER, 'U') ) AS myauth
WHERE myauth.GRANTEE = SESSION_USER
ORDER BY ROLENAME

-- User's roles' tables (replace SESSION_USER with '<user>')
SELECT myauth.GRANTEE, myauth.ROLENAME,
  tabauth.TABSCHEMA, tabauth.TABNAME, tabauth.GRANTEETYPE
FROM TABLE (SYSPROC.AUTH_LIST_ROLES_FOR_AUTHID (SESSION_USER, 'U') ) AS myauth
INNER JOIN SYSCAT.TABAUTH tabauth
  ON (myauth.ROLENAME = tabauth.GRANTEE AND tabauth.GRANTEETYPE = 'R')
  OR (myauth.GRANTEE = tabauth.GRANTEE AND tabauth.GRANTEETYPE = 'U')
WHERE myauth.GRANTEE = SESSION_USER
ORDER BY ROLENAME, TABSCHEMA, TABNAME


-- User's roles' schemas (replace SESSION_USER with '<user>')
SELECT myauth.GRANTEE, myauth.ROLENAME,
  schemaauth.SCHEMANAME
FROM TABLE (SYSPROC.AUTH_LIST_ROLES_FOR_AUTHID (SESSION_USER, 'U') ) AS myauth
INNER JOIN SYSCAT.SCHEMAAUTH schemaauth
  ON (myauth.ROLENAME = schemaauth.GRANTEE AND schemaauth.GRANTEETYPE = 'R')
  OR (myauth.GRANTEE = schemaauth.GRANTEE AND schemaauth.GRANTEETYPE = 'U')
WHERE myauth.GRANTEE = SESSION_USER
ORDER BY ROLENAME, SCHEMANAME


-- Users with both auths
WITH hr_sens_users AS (
  SELECT DISTINCT GRANTEE
  FROM SYSCAT.ROLEAUTH
  WHERE ROLENAME LIKE 'EPM_HR_SENSITIVE%'
    OR ROLENAME LIKE 'EPM_VIEW_HR_SENSITIVE%'
),
hr_users AS (
  SELECT DISTINCT GRANTEE
  FROM SYSCAT.ROLEAUTH
  WHERE ROLENAME = 'EPM_HR_CONSUMER'
    OR ROLENAME = 'EPM_HR_PRODUCER'
    OR ROLENAME = 'EPM_VIEW_HR_CONSUMER'
    OR ROLENAME = 'EPM_VIEW_HR_PRODUCER'
)
SELECT *
FROM hr_sens_users
LEFT JOIN hr_users
  ON hr_sens_users.GRANTEE = hr_users.GRANTEE
