SELECT DISTINCT GRANTEE, TCREATOR, TTNAME
FROM SYSIBM.SYSTABAUTH
WHERE TCREATOR LIKE '%REAL_ESTATE%';

SELECT DISTINCT AUTHID
FROM SYSIBMADM.PRIVILEGES
WHERE AUTHID = SESSION_USER AND AUTHIDTYPE = 'U'
  AND (
    OBJECTSCHEMA LIKE '%REAL_ESTATE%'
    OR OBJECTNAME LIKE '%CSIM%'
  )
WITH UR;

SELECT DISTINCT GRANTEE
FROM SYSCAT.TABAUTH
WHERE (
  TABSCHEMA LIKE '%REAL_ESTATE%'
  OR TABNAME LIKE '%CSIM%'
)
WITH UR;

-- User's roles
SELECT myauth.GRANTEE, myauth.ROLENAME
FROM TABLE (SYSPROC.AUTH_LIST_ROLES_FOR_AUTHID (SESSION_USER, 'U') ) AS myauth
WHERE myauth.GRANTEE = SESSION_USER
ORDER BY ROLENAME

-- User's roles' tables
SELECT myauth.GRANTEE, myauth.ROLENAME,
  tabauth.TABSCHEMA, tabauth.TABNAME, tabauth.GRANTEETYPE
FROM TABLE (SYSPROC.AUTH_LIST_ROLES_FOR_AUTHID (SESSION_USER, 'U') ) AS myauth
LEFT JOIN SYSCAT.TABAUTH tabauth
  ON (myauth.ROLENAME = tabauth.GRANTEE AND tabauth.GRANTEETYPE = 'R')
  OR (myauth.GRANTEE = tabauth.GRANTEE AND tabauth.GRANTEETYPE = 'U')
WHERE myauth.GRANTEE = SESSION_USER
ORDER BY ROLENAME, TABSCHEMA, TABNAME
