/* Meaningless Query */
WITH BLAH AS (
	SELECT *
	FROM (
		VALUES ('Hello world')
	) t1 (col1)
	WHERE 1 = 1
)

/* Storage Size of Tables in Schemas */
SELECT TABNAME,
	TABSCHEMA,
	SUM(DATA_OBJECT_P_SIZE) + SUM(INDEX_OBJECT_P_SIZE) + SUM(LONG_OBJECT_P_SIZE) + SUM(LOB_OBJECT_P_SIZE) + SUM(XML_OBJECT_P_SIZE) SIZE_KB 
FROM SYSIBMADM.ADMINTABINFO
WHERE TABSCHEMA IN ('FNP_A', 'SMS01_A')
GROUP BY TABNAME,
	TABSCHEMA

/* Delete Duplicates */
DELETE FROM
    (SELECT ROWNUMBER() OVER (PARTITION BY COL1, COL2, COL3) AS RN
     FROM SCHEMA.TABLE) AS A
WHERE RN > 1;

/* Looking for Schemas */
SELECT *
FROM SYSCAT.SCHEMATA --SYSIBM.SYSSCHEMAS
WHERE SCHEMANAME = 'BLAH'
WITH UR;

/* Looking for Tables */
SELECT NAME, CREATOR, TYPE, CTIME, BASE_NAME, BASE_SCHEMA, LAST_REGEN_TIME, ALTER_TIME, LASTUSED
FROM SYSIBM.SYSTABLES
WHERE (
	NAME IN 'BLAH'
	OR NAME IN 'BLEH'
	OR NAME IN 'BLEK'
)
WITH UR;

SELECT NAME, CREATOR, TYPE, REMARKS
FROM SYSIBM.SYSTABLES
WHERE NAME IN ('BLAH', 'BLEH')
    AND TYPE IN ('T', 'V')
WITH UR;

/* Looking for Views that SELECT from something else */
SELECT NAME, CREATOR, TYPE, STATEMENT
FROM SYSIBM.SYSVIEWS
WHERE NAME IN ('BLAH', 'BLEH', 'BLEK')
WITH UR;


/* Looking for Columns */
SELECT NAME, TBNAME, TBCREATOR, REMARKS, COLTYPE, LENGTH, NULLS
FROM SYSIBM.SYSCOLUMNS
WHERE (
	NAME IN 'BLAH'
	OR NAME IN 'BLEH'
	OR NAME IN 'BLEK'
)
WITH UR;

/* Look for who ingested */
SELECT *
FROM COEDL_INGESTION.TIMES_V
WHERE BIGSQLSCHEMA = 'SCHEMA'
ORDER BY UPDATED DESC
WITH UR;

/* get row count of table */
SELECT COUNT(*) FROM SCHEMA.TABLE
/* Excel Formula for writing SQL to get row counts for list of tables in Excel 
="SELECT '"&B3&"' TABLE_NAME, COUNT(*) RECORDS FROM WSDIW."&B3&" UNION"
*/

/* get row counts of all tables */
-- Note STATS_TIME might be old, so CARD != COUNT(*)
SELECT TABSCHEMA, TABNAME, TRIM(TABSCHEMA) CONCAT '.' CONCAT TRIM(TABNAME) AS FULL_TABLE_NAME,
    CARD AS ROWS,
    STATS_TIME
FROM SYSCAT.TABLES
ORDER BY CARD DESC 

/* to get table organization (row vs column) from DB2 */
SELECT TABSCHEMA, TABNAME, TYPE, TABLEORG 
FROM SYSCAT.TABLES t 
WHERE TABSCHEMA IN ('WSDIW_A', 'WSDIW_B', 'ECOSYSTEMS_IZ')

/* Get counts of column values for column */
SELECT COLUMN_NAME, COUNT(*)
FROM SCHEMA_NAME.TABLE_NAME
GROUP BY COLUMN_NAME;

/* Cases */
SELECT 
	COLUMN_A, 
	COLUMN_B,
	CASE
	   WHEN ...
	   THEN ...
	   ELSE ...
	END AS COLUMN_C,
	COLUMN_D
FROM SCHEMA.TABLE


/* Learn Alias Table Targets */
SELECT  TYPE,
        TABSCHEMA, 
        TABNAME, 
        BASE_TABSCHEMA, 
        BASE_TABNAME 
FROM SYSCAT.TABLES 
WHERE TABNAME LIKE '%WW_LOAD_SMS%'
WITH UR

/* Learn about schema access */
SELECT * FROM syscat.SCHEMAAUTH WHERE schemaname='EAL_EAL' WITH ur;

/* Create empty table in same structure as other */
CREATE TABLE ACCESS_B.DATA_SOURCE AS (
	SELECT *
	FROM ACCESS_A.DATA_SOURCE ds
	WHERE 1=0
)
WITH DATA;

/* Create View */
CREATE VIEW SCHEMA.VIEW AS (
	SELECT *
	FROM SCHEMA.TABLE
);

/* INSERT slightly edited data from old table into new table */
INSERT INTO ACCESS_B.DATA_SOURCE
SELECT TRIM(BOTH ' ' FROM EMAIL) EMAIL, DATA_SOURCE_ACRONYM
FROM ACCESS_A.DATA_SOURCE

/* Delete data */
DELETE FROM SCHEMA.TABLE
WHERE 1=1 -- all
OR COLUMN = 'BLAH'

/* Grant SELECT privileges */
GRANT SELECT ON SCHEMA.TABLE TO USER "USER";

/* BigSQL Logs */
/* SQL Error [58040]: DB2 SQL Error: SQLCODE=-5105, SQLSTATE=58040, SQLERRMC=BigSQL IO;UNKNOWN;[BSL-5-282fd4bb4];optional group COUNTRYLIST (LI, DRIVER=4.26.14 */
SELECT CAST(LINE AS VARCHAR(300))
FROM TABLE(SYSHADOOP.LOG_ENTRY('BSL-5-282fd4bb4'))
WITH UR;

/* Grant SELECT privilege */
GRANT SELECT ON SCHMEMA.TABLE TO USER "USER_NAME";

/* Looking for duplicates from join */
WITH joined AS (
SELECT
	a.COL1,
	b.COL1,
	b.COL2,
	b.COL3,
	ROWNUMBER() OVER (PARTITION BY a.COL1) AS RN
FROM SCHEMA.TABLE_A a
LEFT JOIN SCHEMA.TABLE_B b
	ON a.COL1 = b.COL2
)
SELECT *
FROM joined
WHERE RN > 1
ORDER BY RN DESC

/* Delete duplicate rows from table */
DELETE FROM
    (SELECT ROWNUMBER() OVER (PARTITION BY EMAIL, META_GEO, META_MKT) AS RN
     FROM ACCESS_A.META_GEO_MKT_EMAIL_ENTLMNTS) AS A
WHERE RN > 1;